services:
  - type: web
    name: global-transfer-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn --app-dir web server:app --host 0.0.0.0 --port 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
