services:
  - type: web
    name: global-transfer-search
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
